import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryWrapper from "@/components/QueryWrapper";
import React from "react";
import AuthContext from "@/components/Auth/AuthContext";
import Navbar from "@/components/Auth/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
          <meta charSet="utf-8"/>
          <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
          <link rel="icon" type="image/jpg" href="/img/lock.jpg"/>
          <title>Secure Key</title>
      </head>
      <body>
      <div className="bg">
          <QueryWrapper>
              <AuthContext>
                  <Navbar />
                  {children}
              </AuthContext>
        </QueryWrapper>
      </div>
      </body>
      </html>
  );
}
